Bump up timeout to 20 minutes
Since 10 minutes is too short for OSX

```
 c9a245e33d92 Extracting [=================>                                 ]  357.1MB/1.048GB
 c9a245e33d92 Extracting [=================>                                 ]  357.6MB/1.048GB
 c9a245e33d92 Extracting [=================>                                 ]  358.2MB/1.048GB
 c9a245e33d92 Extracting [=================>                                 ]  358.7MB/1.048GB
 c9a245e33d92 Extracting [=================>                                 ]  359.3MB/1.048GB
Error: The action 'Download and launch' has timed out after 10 minutes.
```